export const FETCH_STATES="FETCH_STATES"
export const FETCH_STATE_BY_SEARCH="FETCH_STATE_BY_SEARCH"
export const FETCH_STATES_BY_REGION="FETCH_STATES_BY_REGION"
export const THEME_CHANGE="THEME_CHANGE"